/*
* Castaway
*  (C) 1994 - 2002 Martin Doering, Joachim Hoenig
*
* $File$ - 68k logical instructions
*
* This file is distributed under the GPL, version 2 or at your
* option any later version.  See doc/license.txt for details.
*
* revision history
*  23.05.2002  JH  FAST1.0.1 code import: KR -> ANSI, restructuring
*  10.07.2002  JH  Minor clarification when CCR/SR is target (without effect)
*  27.08.2002  JH  ... with effect! Fixed bug. Restructured & clarified.
*/
#ifndef PROTOH
static char     sccsid[] = "$Id: op68klogop.c,v 1.3 2002/08/27 01:21:11 jhoenig Exp $";
#define OPHANDLER
#include "68000.h"
#include "op68k.h"

/*
* Opfuncs.
*/
#define OlogSR(Code, Op, OpSR, Priv, DeclS, Get1, DeclT, Get2, Set2, GetSR, SetSR, retval)\
OperBegin(Code) \
    DeclS(source)\
    DeclT(target)\
    long address;\
    switch ins7 {\
    case 0x0:\
	Get1(source, 0)\
	address = GetMPCW();\
	pc += 2;\
	Get2(address, target)\
	Op(target, source)\
	Set2(address, target)\
	break;\
    case 0x1:\
	Get1(source, 0)\
	address = GetMPCL();\
	pc += 4;\
	Get2(address, target)\
	Op(target, source)\
	Set2(address, target)\
	break;\
    case 0x4:\
	if (Priv && !GetS()) { ExceptionGroup1(PRIV); };\
	Get1(source, 0)\
	GetSR(address2, target)\
	OpSR(target, source)\
	SetSR(address2, target)\
	break;\
    default:\
	ExceptionGroup1(ILLINSTR);\
	break;\
    }\
    OperExit(retval);


#if 1
#define DoAndL(target,source) { __asm__ volatile ( INSTR_BEGIN "and.l %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoEorL(target,source) { __asm__ volatile ( INSTR_BEGIN "eor.l %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoOrL(target,source)  { __asm__ volatile ( INSTR_BEGIN "or.l %2,%0\n\t"  INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#ifndef COLDFIRE
#define DoAndW(target,source) { __asm__ volatile ( INSTR_BEGIN "and.w %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoEorW(target,source) { __asm__ volatile ( INSTR_BEGIN "eor.w %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoOrW(target,source)  { __asm__ volatile ( INSTR_BEGIN "or.w %2,%0\n\t"  INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoAndB(target,source) { __asm__ volatile ( INSTR_BEGIN "and.b %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoEorB(target,source) { __asm__ volatile ( INSTR_BEGIN "eor.b %2,%0\n\t" INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#define DoOrB(target,source)  { __asm__ volatile ( INSTR_BEGIN "or.b %2,%0\n\t"  INSTR_END : "=d"(target) : "0"(target), "d"(source) : "cc" ); };
#endif
#endif

#ifndef DoAndB
#define DoAndB(target,source) target &= source; ClrCVSetNZ(target);
#endif
#ifndef DoAndW
#define DoAndW(target,source) target &= source; ClrCVSetNZ(target);
#endif
#ifndef DoAndL
#define DoAndL(target,source) target &= source; ClrCVSetNZ(target);
#endif
#ifndef DoEorB
#define DoEorB(target,source) target ^= source; ClrCVSetNZ(target);
#endif
#ifndef DoEorW
#define DoEorW(target,source) target ^= source; ClrCVSetNZ(target);
#endif
#ifndef DoEorL
#define DoEorL(target,source) target ^= source; ClrCVSetNZ(target);
#endif
#ifndef DoOrB
#define DoOrB(target,source) target |= source; ClrCVSetNZ(target);
#endif
#ifndef DoOrW
#define DoOrW(target,source) target |= source; ClrCVSetNZ(target);
#endif
#ifndef DoOrL
#define DoOrL(target,source) target |= source; ClrCVSetNZ(target);
#endif

#define DoAndSR(target,source) target &= source;
#define DoEorSR(target,source) target ^= source;
#define DoOrSR(target,source) target |= source;

#else

#define OlogSR(a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12) \
extern void a1();

#endif

OperS(Opc000, DoAndB, DB, SdB, ins7, DB, DR, Cd, 0, GRB, SRB, 4)
OperS(Opc010, DoAndB, DB, SainB, ins7, DB, DR, Cd, 0, GRB, SRB, 8)
OperS(Opc018, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 0, GRB, SRB, 8)
OperS(Opc020, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 0, GRB, SRB, 12)
OperS(Opc028, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 0, GRB, SRB, 12)
Oper (Opc030, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 0, GRB, SRB, 16)
OperS(Opc038, DoAndB, DB, SearB, ins7, DB, DR, Cd, 0, GRB, SRB, 10)
OperS(Opc040, DoAndW, DW, SdW, ins7, DW, DR, Cd, 0, GRW, SRW, 4)
OperS(Opc050, DoAndW, DW, SainW, ins7, DW, DR, Cd, 0, GRW, SRW, 8)
OperS(Opc058, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 0, GRW, SRW, 8)
OperS(Opc060, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 0, GRW, SRW, 12)
OperS(Opc068, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 0, GRW, SRW, 12)
Oper (Opc070, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 0, GRW, SRW, 16)
OperS(Opc078, DoAndW, DW, SearW, ins7, DW, DR, Cd, 0, GRW, SRW, 10)
OperS(Opc080, DoAndL, DL, SdL, ins7, DL, DR, Cd, 0, GRL, SRL, 8)
OperS(Opc090, DoAndL, DL, SainL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Opc098, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Opc0a0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Opc0a8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 0, GRL, SRL, 20)
Oper (Opc0b0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 0, GRL, SRL, 20)
OperS(Opc0b8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 0, GRL, SRL, 18)

Oper (Opc110, DoAndB, DB, SdB, 0, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opc118, DoAndB, DB, SdB, 0, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opc120, DoAndB, DB, SdB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opc128, DoAndB, DB, SdB, 0, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opc130, DoAndB, DB, SdB, 0, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opc138, DoAndB, DB, SdB, 0, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opc150, DoAndW, DW, SdW, 0, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opc158, DoAndW, DW, SdW, 0, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opc160, DoAndW, DW, SdW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opc168, DoAndW, DW, SdW, 0, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opc170, DoAndW, DW, SdW, 0, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opc178, DoAndW, DW, SdW, 0, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opc190, DoAndL, DL, SdL, 0, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opc198, DoAndL, DL, SdL, 0, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opc1a0, DoAndL, DL, SdL, 0, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opc1a8, DoAndL, DL, SdL, 0, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opc1b0, DoAndL, DL, SdL, 0, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opc1b8, DoAndL, DL, SdL, 0, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opc200, DoAndB, DB, SdB, ins7, DB, DR, Cd, 1, GRB, SRB, 4)
OperS(Opc210, DoAndB, DB, SainB, ins7, DB, DR, Cd, 1, GRB, SRB, 8)
OperS(Opc218, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 1, GRB, SRB, 8)
OperS(Opc220, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 1, GRB, SRB, 12)
OperS(Opc228, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 1, GRB, SRB, 12)
Oper (Opc230, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 1, GRB, SRB, 16)
OperS(Opc238, DoAndB, DB, SearB, ins7, DB, DR, Cd, 1, GRB, SRB, 10)
OperS(Opc240, DoAndW, DW, SdW, ins7, DW, DR, Cd, 1, GRW, SRW, 4)
OperS(Opc250, DoAndW, DW, SainW, ins7, DW, DR, Cd, 1, GRW, SRW, 8)
OperS(Opc258, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 1, GRW, SRW, 8)
OperS(Opc260, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 1, GRW, SRW, 12)
OperS(Opc268, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 1, GRW, SRW, 12)
Oper (Opc270, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 1, GRW, SRW, 16)
OperS(Opc278, DoAndW, DW, SearW, ins7, DW, DR, Cd, 1, GRW, SRW, 10)
OperS(Opc280, DoAndL, DL, SdL, ins7, DL, DR, Cd, 1, GRL, SRL, 8)
OperS(Opc290, DoAndL, DL, SainL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Opc298, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Opc2a0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Opc2a8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 1, GRL, SRL, 20)
Oper (Opc2b0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 1, GRL, SRL, 20)
OperS(Opc2b8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 1, GRL, SRL, 18)

Oper (Opc310, DoAndB, DB, SdB, 1, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opc318, DoAndB, DB, SdB, 1, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opc320, DoAndB, DB, SdB, 1, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opc328, DoAndB, DB, SdB, 1, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opc330, DoAndB, DB, SdB, 1, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opc338, DoAndB, DB, SdB, 1, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opc350, DoAndW, DW, SdW, 1, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opc358, DoAndW, DW, SdW, 1, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opc360, DoAndW, DW, SdW, 1, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opc368, DoAndW, DW, SdW, 1, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opc370, DoAndW, DW, SdW, 1, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opc378, DoAndW, DW, SdW, 1, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opc390, DoAndL, DL, SdL, 1, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opc398, DoAndL, DL, SdL, 1, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opc3a0, DoAndL, DL, SdL, 1, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opc3a8, DoAndL, DL, SdL, 1, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opc3b0, DoAndL, DL, SdL, 1, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opc3b8, DoAndL, DL, SdL, 1, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opc400, DoAndB, DB, SdB, ins7, DB, DR, Cd, 2, GRB, SRB, 4)
OperS(Opc410, DoAndB, DB, SainB, ins7, DB, DR, Cd, 2, GRB, SRB, 8)
OperS(Opc418, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 2, GRB, SRB, 8)
OperS(Opc420, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 2, GRB, SRB, 12)
OperS(Opc428, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 2, GRB, SRB, 12)
Oper (Opc430, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 2, GRB, SRB, 16)
OperS(Opc438, DoAndB, DB, SearB, ins7, DB, DR, Cd, 2, GRB, SRB, 10)
OperS(Opc440, DoAndW, DW, SdW, ins7, DW, DR, Cd, 2, GRW, SRW, 4)
OperS(Opc450, DoAndW, DW, SainW, ins7, DW, DR, Cd, 2, GRW, SRW, 8)
OperS(Opc458, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 2, GRW, SRW, 8)
OperS(Opc460, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 2, GRW, SRW, 12)
OperS(Opc468, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 2, GRW, SRW, 12)
Oper (Opc470, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 2, GRW, SRW, 16)
OperS(Opc478, DoAndW, DW, SearW, ins7, DW, DR, Cd, 2, GRW, SRW, 10)
OperS(Opc480, DoAndL, DL, SdL, ins7, DL, DR, Cd, 2, GRL, SRL, 8)
OperS(Opc490, DoAndL, DL, SainL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Opc498, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Opc4a0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Opc4a8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 2, GRL, SRL, 20)
Oper (Opc4b0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 2, GRL, SRL, 20)
OperS(Opc4b8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 2, GRL, SRL, 18)

Oper (Opc510, DoAndB, DB, SdB, 2, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opc518, DoAndB, DB, SdB, 2, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opc520, DoAndB, DB, SdB, 2, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opc528, DoAndB, DB, SdB, 2, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opc530, DoAndB, DB, SdB, 2, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opc538, DoAndB, DB, SdB, 2, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opc550, DoAndW, DW, SdW, 2, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opc558, DoAndW, DW, SdW, 2, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opc560, DoAndW, DW, SdW, 2, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opc568, DoAndW, DW, SdW, 2, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opc570, DoAndW, DW, SdW, 2, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opc578, DoAndW, DW, SdW, 2, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opc590, DoAndL, DL, SdL, 2, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opc598, DoAndL, DL, SdL, 2, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opc5a0, DoAndL, DL, SdL, 2, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opc5a8, DoAndL, DL, SdL, 2, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opc5b0, DoAndL, DL, SdL, 2, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opc5b8, DoAndL, DL, SdL, 2, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opc600, DoAndB, DB, SdB, ins7, DB, DR, Cd, 3, GRB, SRB, 4)
OperS(Opc610, DoAndB, DB, SainB, ins7, DB, DR, Cd, 3, GRB, SRB, 8)
OperS(Opc618, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 3, GRB, SRB, 8)
OperS(Opc620, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 3, GRB, SRB, 12)
OperS(Opc628, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 3, GRB, SRB, 12)
Oper (Opc630, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 3, GRB, SRB, 16)
OperS(Opc638, DoAndB, DB, SearB, ins7, DB, DR, Cd, 3, GRB, SRB, 10)
OperS(Opc640, DoAndW, DW, SdW, ins7, DW, DR, Cd, 3, GRW, SRW, 4)
OperS(Opc650, DoAndW, DW, SainW, ins7, DW, DR, Cd, 3, GRW, SRW, 8)
OperS(Opc658, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 3, GRW, SRW, 8)
OperS(Opc660, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 3, GRW, SRW, 12)
OperS(Opc668, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 3, GRW, SRW, 12)
Oper (Opc670, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 3, GRW, SRW, 16)
OperS(Opc678, DoAndW, DW, SearW, ins7, DW, DR, Cd, 3, GRW, SRW, 10)
OperS(Opc680, DoAndL, DL, SdL, ins7, DL, DR, Cd, 3, GRL, SRL, 8)
OperS(Opc690, DoAndL, DL, SainL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Opc698, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Opc6a0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Opc6a8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 3, GRL, SRL, 20)
Oper (Opc6b0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 3, GRL, SRL, 20)
OperS(Opc6b8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 3, GRL, SRL, 18)

Oper (Opc710, DoAndB, DB, SdB, 3, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opc718, DoAndB, DB, SdB, 3, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opc720, DoAndB, DB, SdB, 3, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opc728, DoAndB, DB, SdB, 3, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opc730, DoAndB, DB, SdB, 3, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opc738, DoAndB, DB, SdB, 3, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opc750, DoAndW, DW, SdW, 3, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opc758, DoAndW, DW, SdW, 3, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opc760, DoAndW, DW, SdW, 3, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opc768, DoAndW, DW, SdW, 3, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opc770, DoAndW, DW, SdW, 3, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opc778, DoAndW, DW, SdW, 3, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opc790, DoAndL, DL, SdL, 3, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opc798, DoAndL, DL, SdL, 3, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opc7a0, DoAndL, DL, SdL, 3, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opc7a8, DoAndL, DL, SdL, 3, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opc7b0, DoAndL, DL, SdL, 3, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opc7b8, DoAndL, DL, SdL, 3, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opc800, DoAndB, DB, SdB, ins7, DB, DR, Cd, 4, GRB, SRB, 4)
OperS(Opc810, DoAndB, DB, SainB, ins7, DB, DR, Cd, 4, GRB, SRB, 8)
OperS(Opc818, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 4, GRB, SRB, 8)
OperS(Opc820, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 4, GRB, SRB, 12)
OperS(Opc828, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 4, GRB, SRB, 12)
Oper (Opc830, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 4, GRB, SRB, 16)
OperS(Opc838, DoAndB, DB, SearB, ins7, DB, DR, Cd, 4, GRB, SRB, 10)
OperS(Opc840, DoAndW, DW, SdW, ins7, DW, DR, Cd, 4, GRW, SRW, 4)
OperS(Opc850, DoAndW, DW, SainW, ins7, DW, DR, Cd, 4, GRW, SRW, 8)
OperS(Opc858, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 4, GRW, SRW, 8)
OperS(Opc860, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 4, GRW, SRW, 12)
OperS(Opc868, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 4, GRW, SRW, 12)
Oper (Opc870, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 4, GRW, SRW, 16)
OperS(Opc878, DoAndW, DW, SearW, ins7, DW, DR, Cd, 4, GRW, SRW, 10)
OperS(Opc880, DoAndL, DL, SdL, ins7, DL, DR, Cd, 4, GRL, SRL, 8)
OperS(Opc890, DoAndL, DL, SainL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Opc898, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Opc8a0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Opc8a8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 4, GRL, SRL, 20)
Oper (Opc8b0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 4, GRL, SRL, 20)
OperS(Opc8b8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 4, GRL, SRL, 18)

Oper (Opc910, DoAndB, DB, SdB, 4, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opc918, DoAndB, DB, SdB, 4, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opc920, DoAndB, DB, SdB, 4, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opc928, DoAndB, DB, SdB, 4, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opc930, DoAndB, DB, SdB, 4, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opc938, DoAndB, DB, SdB, 4, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opc950, DoAndW, DW, SdW, 4, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opc958, DoAndW, DW, SdW, 4, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opc960, DoAndW, DW, SdW, 4, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opc968, DoAndW, DW, SdW, 4, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opc970, DoAndW, DW, SdW, 4, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opc978, DoAndW, DW, SdW, 4, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opc990, DoAndL, DL, SdL, 4, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opc998, DoAndL, DL, SdL, 4, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opc9a0, DoAndL, DL, SdL, 4, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opc9a8, DoAndL, DL, SdL, 4, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opc9b0, DoAndL, DL, SdL, 4, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opc9b8, DoAndL, DL, SdL, 4, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opca00, DoAndB, DB, SdB, ins7, DB, DR, Cd, 5, GRB, SRB, 4)
OperS(Opca10, DoAndB, DB, SainB, ins7, DB, DR, Cd, 5, GRB, SRB, 8)
OperS(Opca18, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 5, GRB, SRB, 8)
OperS(Opca20, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 5, GRB, SRB, 12)
OperS(Opca28, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 5, GRB, SRB, 12)
Oper (Opca30, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 5, GRB, SRB, 16)
OperS(Opca38, DoAndB, DB, SearB, ins7, DB, DR, Cd, 5, GRB, SRB, 10)
OperS(Opca40, DoAndW, DW, SdW, ins7, DW, DR, Cd, 5, GRW, SRW, 4)
OperS(Opca50, DoAndW, DW, SainW, ins7, DW, DR, Cd, 5, GRW, SRW, 8)
OperS(Opca58, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 5, GRW, SRW, 8)
OperS(Opca60, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 5, GRW, SRW, 12)
OperS(Opca68, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 5, GRW, SRW, 12)
Oper (Opca70, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 5, GRW, SRW, 16)
OperS(Opca78, DoAndW, DW, SearW, ins7, DW, DR, Cd, 5, GRW, SRW, 10)
OperS(Opca80, DoAndL, DL, SdL, ins7, DL, DR, Cd, 5, GRL, SRL, 8)
OperS(Opca90, DoAndL, DL, SainL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Opca98, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Opcaa0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Opcaa8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 5, GRL, SRL, 20)
Oper (Opcab0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 5, GRL, SRL, 20)
OperS(Opcab8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 5, GRL, SRL, 18)

Oper (Opcb10, DoAndB, DB, SdB, 5, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opcb18, DoAndB, DB, SdB, 5, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opcb20, DoAndB, DB, SdB, 5, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opcb28, DoAndB, DB, SdB, 5, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opcb30, DoAndB, DB, SdB, 5, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opcb38, DoAndB, DB, SdB, 5, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opcb50, DoAndW, DW, SdW, 5, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opcb58, DoAndW, DW, SdW, 5, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opcb60, DoAndW, DW, SdW, 5, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opcb68, DoAndW, DW, SdW, 5, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opcb70, DoAndW, DW, SdW, 5, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opcb78, DoAndW, DW, SdW, 5, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opcb90, DoAndL, DL, SdL, 5, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opcb98, DoAndL, DL, SdL, 5, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opcba0, DoAndL, DL, SdL, 5, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opcba8, DoAndL, DL, SdL, 5, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opcbb0, DoAndL, DL, SdL, 5, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opcbb8, DoAndL, DL, SdL, 5, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opcc00, DoAndB, DB, SdB, ins7, DB, DR, Cd, 6, GRB, SRB, 4)
OperS(Opcc10, DoAndB, DB, SainB, ins7, DB, DR, Cd, 6, GRB, SRB, 8)
OperS(Opcc18, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 6, GRB, SRB, 8)
OperS(Opcc20, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 6, GRB, SRB, 12)
OperS(Opcc28, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 6, GRB, SRB, 12)
Oper (Opcc30, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 6, GRB, SRB, 16)
OperS(Opcc38, DoAndB, DB, SearB, ins7, DB, DR, Cd, 6, GRB, SRB, 10)
OperS(Opcc40, DoAndW, DW, SdW, ins7, DW, DR, Cd, 6, GRW, SRW, 4)
OperS(Opcc50, DoAndW, DW, SainW, ins7, DW, DR, Cd, 6, GRW, SRW, 8)
OperS(Opcc58, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 6, GRW, SRW, 8)
OperS(Opcc60, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 6, GRW, SRW, 12)
OperS(Opcc68, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 6, GRW, SRW, 12)
Oper (Opcc70, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 6, GRW, SRW, 16)
OperS(Opcc78, DoAndW, DW, SearW, ins7, DW, DR, Cd, 6, GRW, SRW, 10)
OperS(Opcc80, DoAndL, DL, SdL, ins7, DL, DR, Cd, 6, GRL, SRL, 8)
OperS(Opcc90, DoAndL, DL, SainL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Opcc98, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Opcca0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Opcca8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 6, GRL, SRL, 20)
Oper (Opccb0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 6, GRL, SRL, 20)
OperS(Opccb8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 6, GRL, SRL, 18)

Oper (Opcd10, DoAndB, DB, SdB, 6, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opcd18, DoAndB, DB, SdB, 6, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opcd20, DoAndB, DB, SdB, 6, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opcd28, DoAndB, DB, SdB, 6, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opcd30, DoAndB, DB, SdB, 6, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opcd38, DoAndB, DB, SdB, 6, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opcd50, DoAndW, DW, SdW, 6, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opcd58, DoAndW, DW, SdW, 6, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opcd60, DoAndW, DW, SdW, 6, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opcd68, DoAndW, DW, SdW, 6, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opcd70, DoAndW, DW, SdW, 6, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opcd78, DoAndW, DW, SdW, 6, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opcd90, DoAndL, DL, SdL, 6, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opcd98, DoAndL, DL, SdL, 6, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opcda0, DoAndL, DL, SdL, 6, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opcda8, DoAndL, DL, SdL, 6, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opcdb0, DoAndL, DL, SdL, 6, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opcdb8, DoAndL, DL, SdL, 6, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opce00, DoAndB, DB, SdB, ins7, DB, DR, Cd, 7, GRB, SRB, 4)
OperS(Opce10, DoAndB, DB, SainB, ins7, DB, DR, Cd, 7, GRB, SRB, 8)
OperS(Opce18, DoAndB, DB, SaipB, ins7, DB, DR, Cd, 7, GRB, SRB, 8)
OperS(Opce20, DoAndB, DB, SmaiB, ins7, DB, DR, Cd, 7, GRB, SRB, 12)
OperS(Opce28, DoAndB, DB, SdaiB, ins7, DB, DR, Cd, 7, GRB, SRB, 12)
Oper (Opce30, DoAndB, DB, SaixB, ins7, DB, DR, Cd, 7, GRB, SRB, 16)
OperS(Opce38, DoAndB, DB, SearB, ins7, DB, DR, Cd, 7, GRB, SRB, 10)
OperS(Opce40, DoAndW, DW, SdW, ins7, DW, DR, Cd, 7, GRW, SRW, 4)
OperS(Opce50, DoAndW, DW, SainW, ins7, DW, DR, Cd, 7, GRW, SRW, 8)
OperS(Opce58, DoAndW, DW, SaipW, ins7, DW, DR, Cd, 7, GRW, SRW, 8)
OperS(Opce60, DoAndW, DW, SmaiW, ins7, DW, DR, Cd, 7, GRW, SRW, 12)
OperS(Opce68, DoAndW, DW, SdaiW, ins7, DW, DR, Cd, 7, GRW, SRW, 12)
Oper (Opce70, DoAndW, DW, SaixW, ins7, DW, DR, Cd, 7, GRW, SRW, 16)
OperS(Opce78, DoAndW, DW, SearW, ins7, DW, DR, Cd, 7, GRW, SRW, 10)
OperS(Opce80, DoAndL, DL, SdL, ins7, DL, DR, Cd, 7, GRL, SRL, 8)
OperS(Opce90, DoAndL, DL, SainL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Opce98, DoAndL, DL, SaipL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Opcea0, DoAndL, DL, SmaiL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Opcea8, DoAndL, DL, SdaiL, ins7, DL, DR, Cd, 7, GRL, SRL, 20)
Oper (Opceb0, DoAndL, DL, SaixL, ins7, DL, DR, Cd, 7, GRL, SRL, 20)
OperS(Opceb8, DoAndL, DL, SearL, ins7, DL, DR, Cd, 7, GRL, SRL, 18)

Oper (Opcf10, DoAndB, DB, SdB, 7, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opcf18, DoAndB, DB, SdB, 7, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opcf20, DoAndB, DB, SdB, 7, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opcf28, DoAndB, DB, SdB, 7, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opcf30, DoAndB, DB, SdB, 7, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opcf38, DoAndB, DB, SdB, 7, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Opcf50, DoAndW, DW, SdW, 7, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opcf58, DoAndW, DW, SdW, 7, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opcf60, DoAndW, DW, SdW, 7, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opcf68, DoAndW, DW, SdW, 7, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opcf70, DoAndW, DW, SdW, 7, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opcf78, DoAndW, DW, SdW, 7, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Opcf90, DoAndL, DL, SdL, 7, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opcf98, DoAndL, DL, SdL, 7, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opcfa0, DoAndL, DL, SdL, 7, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opcfa8, DoAndL, DL, SdL, 7, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opcfb0, DoAndL, DL, SdL, 7, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opcfb8, DoAndL, DL, SdL, 7, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8000, DoOrB, DB, SdB, ins7, DB, DR, Cd, 0, GRB, SRB, 4)
OperS(Op8010, DoOrB, DB, SainB, ins7, DB, DR, Cd, 0, GRB, SRB, 8)
OperS(Op8018, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 0, GRB, SRB, 8)
OperS(Op8020, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 0, GRB, SRB, 12)
OperS(Op8028, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 0, GRB, SRB, 12)
Oper (Op8030, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 0, GRB, SRB, 16)
OperS(Op8038, DoOrB, DB, SearB, ins7, DB, DR, Cd, 0, GRB, SRB, 10)
OperS(Op8040, DoOrW, DW, SdW, ins7, DW, DR, Cd, 0, GRW, SRW, 4)
OperS(Op8050, DoOrW, DW, SainW, ins7, DW, DR, Cd, 0, GRW, SRW, 8)
OperS(Op8058, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 0, GRW, SRW, 8)
OperS(Op8060, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 0, GRW, SRW, 12)
OperS(Op8068, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 0, GRW, SRW, 12)
Oper (Op8070, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 0, GRW, SRW, 16)
OperS(Op8078, DoOrW, DW, SearW, ins7, DW, DR, Cd, 0, GRW, SRW, 10)
OperS(Op8080, DoOrL, DL, SdL, ins7, DL, DR, Cd, 0, GRL, SRL, 8)
OperS(Op8090, DoOrL, DL, SainL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Op8098, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Op80a0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 0, GRL, SRL, 16)
OperS(Op80a8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 0, GRL, SRL, 20)
Oper (Op80b0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 0, GRL, SRL, 20)
OperS(Op80b8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 0, GRL, SRL, 18)

Oper (Op8110, DoOrB, DB, SdB, 0, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8118, DoOrB, DB, SdB, 0, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8120, DoOrB, DB, SdB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8128, DoOrB, DB, SdB, 0, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8130, DoOrB, DB, SdB, 0, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8138, DoOrB, DB, SdB, 0, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8150, DoOrW, DW, SdW, 0, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8158, DoOrW, DW, SdW, 0, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8160, DoOrW, DW, SdW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8168, DoOrW, DW, SdW, 0, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8170, DoOrW, DW, SdW, 0, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8178, DoOrW, DW, SdW, 0, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8190, DoOrL, DL, SdL, 0, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8198, DoOrL, DL, SdL, 0, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op81a0, DoOrL, DL, SdL, 0, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op81a8, DoOrL, DL, SdL, 0, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op81b0, DoOrL, DL, SdL, 0, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op81b8, DoOrL, DL, SdL, 0, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8200, DoOrB, DB, SdB, ins7, DB, DR, Cd, 1, GRB, SRB, 4)
OperS(Op8210, DoOrB, DB, SainB, ins7, DB, DR, Cd, 1, GRB, SRB, 8)
OperS(Op8218, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 1, GRB, SRB, 8)
OperS(Op8220, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 1, GRB, SRB, 12)
OperS(Op8228, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 1, GRB, SRB, 12)
Oper (Op8230, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 1, GRB, SRB, 16)
OperS(Op8238, DoOrB, DB, SearB, ins7, DB, DR, Cd, 1, GRB, SRB, 10)
OperS(Op8240, DoOrW, DW, SdW, ins7, DW, DR, Cd, 1, GRW, SRW, 4)
OperS(Op8250, DoOrW, DW, SainW, ins7, DW, DR, Cd, 1, GRW, SRW, 8)
OperS(Op8258, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 1, GRW, SRW, 8)
OperS(Op8260, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 1, GRW, SRW, 12)
OperS(Op8268, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 1, GRW, SRW, 12)
Oper (Op8270, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 1, GRW, SRW, 16)
OperS(Op8278, DoOrW, DW, SearW, ins7, DW, DR, Cd, 1, GRW, SRW, 10)
OperS(Op8280, DoOrL, DL, SdL, ins7, DL, DR, Cd, 1, GRL, SRL, 8)
OperS(Op8290, DoOrL, DL, SainL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Op8298, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Op82a0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 1, GRL, SRL, 16)
OperS(Op82a8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 1, GRL, SRL, 20)
Oper (Op82b0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 1, GRL, SRL, 20)
OperS(Op82b8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 1, GRL, SRL, 18)

Oper (Op8310, DoOrB, DB, SdB, 1, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8318, DoOrB, DB, SdB, 1, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8320, DoOrB, DB, SdB, 1, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8328, DoOrB, DB, SdB, 1, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8330, DoOrB, DB, SdB, 1, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8338, DoOrB, DB, SdB, 1, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8350, DoOrW, DW, SdW, 1, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8358, DoOrW, DW, SdW, 1, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8360, DoOrW, DW, SdW, 1, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8368, DoOrW, DW, SdW, 1, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8370, DoOrW, DW, SdW, 1, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8378, DoOrW, DW, SdW, 1, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8390, DoOrL, DL, SdL, 1, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8398, DoOrL, DL, SdL, 1, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op83a0, DoOrL, DL, SdL, 1, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op83a8, DoOrL, DL, SdL, 1, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op83b0, DoOrL, DL, SdL, 1, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op83b8, DoOrL, DL, SdL, 1, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8400, DoOrB, DB, SdB, ins7, DB, DR, Cd, 2, GRB, SRB, 4)
OperS(Op8410, DoOrB, DB, SainB, ins7, DB, DR, Cd, 2, GRB, SRB, 8)
OperS(Op8418, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 2, GRB, SRB, 8)
OperS(Op8420, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 2, GRB, SRB, 12)
OperS(Op8428, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 2, GRB, SRB, 12)
Oper (Op8430, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 2, GRB, SRB, 16)
OperS(Op8438, DoOrB, DB, SearB, ins7, DB, DR, Cd, 2, GRB, SRB, 10)
OperS(Op8440, DoOrW, DW, SdW, ins7, DW, DR, Cd, 2, GRW, SRW, 4)
OperS(Op8450, DoOrW, DW, SainW, ins7, DW, DR, Cd, 2, GRW, SRW, 8)
OperS(Op8458, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 2, GRW, SRW, 8)
OperS(Op8460, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 2, GRW, SRW, 12)
OperS(Op8468, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 2, GRW, SRW, 12)
Oper (Op8470, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 2, GRW, SRW, 16)
OperS(Op8478, DoOrW, DW, SearW, ins7, DW, DR, Cd, 2, GRW, SRW, 10)
OperS(Op8480, DoOrL, DL, SdL, ins7, DL, DR, Cd, 2, GRL, SRL, 8)
OperS(Op8490, DoOrL, DL, SainL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Op8498, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Op84a0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 2, GRL, SRL, 16)
OperS(Op84a8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 2, GRL, SRL, 20)
Oper (Op84b0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 2, GRL, SRL, 20)
OperS(Op84b8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 2, GRL, SRL, 18)

Oper (Op8510, DoOrB, DB, SdB, 2, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8518, DoOrB, DB, SdB, 2, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8520, DoOrB, DB, SdB, 2, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8528, DoOrB, DB, SdB, 2, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8530, DoOrB, DB, SdB, 2, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8538, DoOrB, DB, SdB, 2, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8550, DoOrW, DW, SdW, 2, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8558, DoOrW, DW, SdW, 2, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8560, DoOrW, DW, SdW, 2, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8568, DoOrW, DW, SdW, 2, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8570, DoOrW, DW, SdW, 2, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8578, DoOrW, DW, SdW, 2, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8590, DoOrL, DL, SdL, 2, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8598, DoOrL, DL, SdL, 2, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op85a0, DoOrL, DL, SdL, 2, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op85a8, DoOrL, DL, SdL, 2, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op85b0, DoOrL, DL, SdL, 2, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op85b8, DoOrL, DL, SdL, 2, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8600, DoOrB, DB, SdB, ins7, DB, DR, Cd, 3, GRB, SRB, 4)
OperS(Op8610, DoOrB, DB, SainB, ins7, DB, DR, Cd, 3, GRB, SRB, 8)
OperS(Op8618, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 3, GRB, SRB, 8)
OperS(Op8620, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 3, GRB, SRB, 12)
OperS(Op8628, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 3, GRB, SRB, 12)
Oper (Op8630, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 3, GRB, SRB, 16)
OperS(Op8638, DoOrB, DB, SearB, ins7, DB, DR, Cd, 3, GRB, SRB, 10)
OperS(Op8640, DoOrW, DW, SdW, ins7, DW, DR, Cd, 3, GRW, SRW, 4)
OperS(Op8650, DoOrW, DW, SainW, ins7, DW, DR, Cd, 3, GRW, SRW, 8)
OperS(Op8658, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 3, GRW, SRW, 8)
OperS(Op8660, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 3, GRW, SRW, 12)
OperS(Op8668, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 3, GRW, SRW, 12)
Oper (Op8670, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 3, GRW, SRW, 16)
OperS(Op8678, DoOrW, DW, SearW, ins7, DW, DR, Cd, 3, GRW, SRW, 10)
OperS(Op8680, DoOrL, DL, SdL, ins7, DL, DR, Cd, 3, GRL, SRL, 8)
OperS(Op8690, DoOrL, DL, SainL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Op8698, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Op86a0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 3, GRL, SRL, 16)
OperS(Op86a8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 3, GRL, SRL, 20)
Oper (Op86b0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 3, GRL, SRL, 20)
OperS(Op86b8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 3, GRL, SRL, 18)

Oper (Op8710, DoOrB, DB, SdB, 3, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8718, DoOrB, DB, SdB, 3, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8720, DoOrB, DB, SdB, 3, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8728, DoOrB, DB, SdB, 3, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8730, DoOrB, DB, SdB, 3, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8738, DoOrB, DB, SdB, 3, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8750, DoOrW, DW, SdW, 3, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8758, DoOrW, DW, SdW, 3, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8760, DoOrW, DW, SdW, 3, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8768, DoOrW, DW, SdW, 3, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8770, DoOrW, DW, SdW, 3, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8778, DoOrW, DW, SdW, 3, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8790, DoOrL, DL, SdL, 3, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8798, DoOrL, DL, SdL, 3, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op87a0, DoOrL, DL, SdL, 3, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op87a8, DoOrL, DL, SdL, 3, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op87b0, DoOrL, DL, SdL, 3, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op87b8, DoOrL, DL, SdL, 3, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8800, DoOrB, DB, SdB, ins7, DB, DR, Cd, 4, GRB, SRB, 4)
OperS(Op8810, DoOrB, DB, SainB, ins7, DB, DR, Cd, 4, GRB, SRB, 8)
OperS(Op8818, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 4, GRB, SRB, 8)
OperS(Op8820, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 4, GRB, SRB, 12)
OperS(Op8828, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 4, GRB, SRB, 12)
Oper (Op8830, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 4, GRB, SRB, 16)
OperS(Op8838, DoOrB, DB, SearB, ins7, DB, DR, Cd, 4, GRB, SRB, 10)
OperS(Op8840, DoOrW, DW, SdW, ins7, DW, DR, Cd, 4, GRW, SRW, 4)
OperS(Op8850, DoOrW, DW, SainW, ins7, DW, DR, Cd, 4, GRW, SRW, 8)
OperS(Op8858, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 4, GRW, SRW, 8)
OperS(Op8860, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 4, GRW, SRW, 12)
OperS(Op8868, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 4, GRW, SRW, 12)
Oper (Op8870, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 4, GRW, SRW, 16)
OperS(Op8878, DoOrW, DW, SearW, ins7, DW, DR, Cd, 4, GRW, SRW, 10)
OperS(Op8880, DoOrL, DL, SdL, ins7, DL, DR, Cd, 4, GRL, SRL, 8)
OperS(Op8890, DoOrL, DL, SainL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Op8898, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Op88a0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 4, GRL, SRL, 16)
OperS(Op88a8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 4, GRL, SRL, 20)
Oper (Op88b0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 4, GRL, SRL, 20)
OperS(Op88b8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 4, GRL, SRL, 18)

Oper (Op8910, DoOrB, DB, SdB, 4, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8918, DoOrB, DB, SdB, 4, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8920, DoOrB, DB, SdB, 4, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8928, DoOrB, DB, SdB, 4, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8930, DoOrB, DB, SdB, 4, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8938, DoOrB, DB, SdB, 4, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8950, DoOrW, DW, SdW, 4, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8958, DoOrW, DW, SdW, 4, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8960, DoOrW, DW, SdW, 4, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8968, DoOrW, DW, SdW, 4, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8970, DoOrW, DW, SdW, 4, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8978, DoOrW, DW, SdW, 4, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8990, DoOrL, DL, SdL, 4, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8998, DoOrL, DL, SdL, 4, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op89a0, DoOrL, DL, SdL, 4, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op89a8, DoOrL, DL, SdL, 4, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op89b0, DoOrL, DL, SdL, 4, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op89b8, DoOrL, DL, SdL, 4, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8a00, DoOrB, DB, SdB, ins7, DB, DR, Cd, 5, GRB, SRB, 4)
OperS(Op8a10, DoOrB, DB, SainB, ins7, DB, DR, Cd, 5, GRB, SRB, 8)
OperS(Op8a18, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 5, GRB, SRB, 8)
OperS(Op8a20, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 5, GRB, SRB, 12)
OperS(Op8a28, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 5, GRB, SRB, 12)
Oper (Op8a30, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 5, GRB, SRB, 16)
OperS(Op8a38, DoOrB, DB, SearB, ins7, DB, DR, Cd, 5, GRB, SRB, 10)
OperS(Op8a40, DoOrW, DW, SdW, ins7, DW, DR, Cd, 5, GRW, SRW, 4)
OperS(Op8a50, DoOrW, DW, SainW, ins7, DW, DR, Cd, 5, GRW, SRW, 8)
OperS(Op8a58, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 5, GRW, SRW, 8)
OperS(Op8a60, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 5, GRW, SRW, 12)
OperS(Op8a68, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 5, GRW, SRW, 12)
Oper (Op8a70, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 5, GRW, SRW, 16)
OperS(Op8a78, DoOrW, DW, SearW, ins7, DW, DR, Cd, 5, GRW, SRW, 10)
OperS(Op8a80, DoOrL, DL, SdL, ins7, DL, DR, Cd, 5, GRL, SRL, 8)
OperS(Op8a90, DoOrL, DL, SainL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Op8a98, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Op8aa0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 5, GRL, SRL, 16)
OperS(Op8aa8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 5, GRL, SRL, 20)
Oper (Op8ab0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 5, GRL, SRL, 20)
OperS(Op8ab8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 5, GRL, SRL, 18)

Oper (Op8b10, DoOrB, DB, SdB, 5, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8b18, DoOrB, DB, SdB, 5, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8b20, DoOrB, DB, SdB, 5, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8b28, DoOrB, DB, SdB, 5, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8b30, DoOrB, DB, SdB, 5, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8b38, DoOrB, DB, SdB, 5, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8b50, DoOrW, DW, SdW, 5, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8b58, DoOrW, DW, SdW, 5, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8b60, DoOrW, DW, SdW, 5, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8b68, DoOrW, DW, SdW, 5, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8b70, DoOrW, DW, SdW, 5, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8b78, DoOrW, DW, SdW, 5, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8b90, DoOrL, DL, SdL, 5, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8b98, DoOrL, DL, SdL, 5, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op8ba0, DoOrL, DL, SdL, 5, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op8ba8, DoOrL, DL, SdL, 5, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op8bb0, DoOrL, DL, SdL, 5, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op8bb8, DoOrL, DL, SdL, 5, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8c00, DoOrB, DB, SdB, ins7, DB, DR, Cd, 6, GRB, SRB, 4)
OperS(Op8c10, DoOrB, DB, SainB, ins7, DB, DR, Cd, 6, GRB, SRB, 8)
OperS(Op8c18, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 6, GRB, SRB, 8)
OperS(Op8c20, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 6, GRB, SRB, 12)
OperS(Op8c28, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 6, GRB, SRB, 12)
Oper (Op8c30, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 6, GRB, SRB, 16)
OperS(Op8c38, DoOrB, DB, SearB, ins7, DB, DR, Cd, 6, GRB, SRB, 10)
OperS(Op8c40, DoOrW, DW, SdW, ins7, DW, DR, Cd, 6, GRW, SRW, 4)
OperS(Op8c50, DoOrW, DW, SainW, ins7, DW, DR, Cd, 6, GRW, SRW, 8)
OperS(Op8c58, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 6, GRW, SRW, 8)
OperS(Op8c60, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 6, GRW, SRW, 12)
OperS(Op8c68, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 6, GRW, SRW, 12)
Oper (Op8c70, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 6, GRW, SRW, 16)
OperS(Op8c78, DoOrW, DW, SearW, ins7, DW, DR, Cd, 6, GRW, SRW, 10)
OperS(Op8c80, DoOrL, DL, SdL, ins7, DL, DR, Cd, 6, GRL, SRL, 8)
OperS(Op8c90, DoOrL, DL, SainL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Op8c98, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Op8ca0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 6, GRL, SRL, 16)
OperS(Op8ca8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 6, GRL, SRL, 20)
Oper (Op8cb0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 6, GRL, SRL, 20)
OperS(Op8cb8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 6, GRL, SRL, 18)

Oper (Op8d10, DoOrB, DB, SdB, 6, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8d18, DoOrB, DB, SdB, 6, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8d20, DoOrB, DB, SdB, 6, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8d28, DoOrB, DB, SdB, 6, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8d30, DoOrB, DB, SdB, 6, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8d38, DoOrB, DB, SdB, 6, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8d50, DoOrW, DW, SdW, 6, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8d58, DoOrW, DW, SdW, 6, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8d60, DoOrW, DW, SdW, 6, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8d68, DoOrW, DW, SdW, 6, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8d70, DoOrW, DW, SdW, 6, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8d78, DoOrW, DW, SdW, 6, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8d90, DoOrL, DL, SdL, 6, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8d98, DoOrL, DL, SdL, 6, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op8da0, DoOrL, DL, SdL, 6, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op8da8, DoOrL, DL, SdL, 6, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op8db0, DoOrL, DL, SdL, 6, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op8db8, DoOrL, DL, SdL, 6, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Op8e00, DoOrB, DB, SdB, ins7, DB, DR, Cd, 7, GRB, SRB, 4)
OperS(Op8e10, DoOrB, DB, SainB, ins7, DB, DR, Cd, 7, GRB, SRB, 8)
OperS(Op8e18, DoOrB, DB, SaipB, ins7, DB, DR, Cd, 7, GRB, SRB, 8)
OperS(Op8e20, DoOrB, DB, SmaiB, ins7, DB, DR, Cd, 7, GRB, SRB, 12)
OperS(Op8e28, DoOrB, DB, SdaiB, ins7, DB, DR, Cd, 7, GRB, SRB, 12)
Oper (Op8e30, DoOrB, DB, SaixB, ins7, DB, DR, Cd, 7, GRB, SRB, 16)
OperS(Op8e38, DoOrB, DB, SearB, ins7, DB, DR, Cd, 7, GRB, SRB, 10)
OperS(Op8e40, DoOrW, DW, SdW, ins7, DW, DR, Cd, 7, GRW, SRW, 4)
OperS(Op8e50, DoOrW, DW, SainW, ins7, DW, DR, Cd, 7, GRW, SRW, 8)
OperS(Op8e58, DoOrW, DW, SaipW, ins7, DW, DR, Cd, 7, GRW, SRW, 8)
OperS(Op8e60, DoOrW, DW, SmaiW, ins7, DW, DR, Cd, 7, GRW, SRW, 12)
OperS(Op8e68, DoOrW, DW, SdaiW, ins7, DW, DR, Cd, 7, GRW, SRW, 12)
Oper (Op8e70, DoOrW, DW, SaixW, ins7, DW, DR, Cd, 7, GRW, SRW, 16)
OperS(Op8e78, DoOrW, DW, SearW, ins7, DW, DR, Cd, 7, GRW, SRW, 10)
OperS(Op8e80, DoOrL, DL, SdL, ins7, DL, DR, Cd, 7, GRL, SRL, 8)
OperS(Op8e90, DoOrL, DL, SainL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Op8e98, DoOrL, DL, SaipL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Op8ea0, DoOrL, DL, SmaiL, ins7, DL, DR, Cd, 7, GRL, SRL, 16)
OperS(Op8ea8, DoOrL, DL, SdaiL, ins7, DL, DR, Cd, 7, GRL, SRL, 20)
Oper (Op8eb0, DoOrL, DL, SaixL, ins7, DL, DR, Cd, 7, GRL, SRL, 20)
OperS(Op8eb8, DoOrL, DL, SearL, ins7, DL, DR, Cd, 7, GRL, SRL, 18)

Oper (Op8f10, DoOrB, DB, SdB, 7, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Op8f18, DoOrB, DB, SdB, 7, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Op8f20, DoOrB, DB, SdB, 7, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Op8f28, DoOrB, DB, SdB, 7, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Op8f30, DoOrB, DB, SdB, 7, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Op8f38, DoOrB, DB, SdB, 7, DB, DA, Ceaw, ins7, GMB, SMB, 18)
Oper (Op8f50, DoOrW, DW, SdW, 7, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Op8f58, DoOrW, DW, SdW, 7, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Op8f60, DoOrW, DW, SdW, 7, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Op8f68, DoOrW, DW, SdW, 7, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Op8f70, DoOrW, DW, SdW, 7, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Op8f78, DoOrW, DW, SdW, 7, DW, DA, Ceaw, ins7, GMW, SMW, 18)
Oper (Op8f90, DoOrL, DL, SdL, 7, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Op8f98, DoOrL, DL, SdL, 7, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Op8fa0, DoOrL, DL, SdL, 7, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Op8fa8, DoOrL, DL, SdL, 7, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Op8fb0, DoOrL, DL, SdL, 7, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Op8fb8, DoOrL, DL, SdL, 7, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opb100, DoEorB, DB, SdB, 0, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opb110, DoEorB, DB, SdB, 0, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opb118, DoEorB, DB, SdB, 0, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opb120, DoEorB, DB, SdB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opb128, DoEorB, DB, SdB, 0, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opb130, DoEorB, DB, SdB, 0, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opb138, DoEorB, DB, SdB, 0, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opb140, DoEorW, DW, SdW, 0, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opb150, DoEorW, DW, SdW, 0, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opb158, DoEorW, DW, SdW, 0, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opb160, DoEorW, DW, SdW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opb168, DoEorW, DW, SdW, 0, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opb170, DoEorW, DW, SdW, 0, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opb178, DoEorW, DW, SdW, 0, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opb180, DoEorL, DL, SdL, 0, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opb190, DoEorL, DL, SdL, 0, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opb198, DoEorL, DL, SdL, 0, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opb1a0, DoEorL, DL, SdL, 0, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opb1a8, DoEorL, DL, SdL, 0, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opb1b0, DoEorL, DL, SdL, 0, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opb1b8, DoEorL, DL, SdL, 0, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opb300, DoEorB, DB, SdB, 1, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opb310, DoEorB, DB, SdB, 1, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opb318, DoEorB, DB, SdB, 1, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opb320, DoEorB, DB, SdB, 1, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opb328, DoEorB, DB, SdB, 1, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opb330, DoEorB, DB, SdB, 1, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opb338, DoEorB, DB, SdB, 1, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opb340, DoEorW, DW, SdW, 1, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opb350, DoEorW, DW, SdW, 1, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opb358, DoEorW, DW, SdW, 1, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opb360, DoEorW, DW, SdW, 1, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opb368, DoEorW, DW, SdW, 1, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opb370, DoEorW, DW, SdW, 1, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opb378, DoEorW, DW, SdW, 1, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opb380, DoEorL, DL, SdL, 1, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opb390, DoEorL, DL, SdL, 1, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opb398, DoEorL, DL, SdL, 1, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opb3a0, DoEorL, DL, SdL, 1, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opb3a8, DoEorL, DL, SdL, 1, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opb3b0, DoEorL, DL, SdL, 1, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opb3b8, DoEorL, DL, SdL, 1, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opb500, DoEorB, DB, SdB, 2, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opb510, DoEorB, DB, SdB, 2, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opb518, DoEorB, DB, SdB, 2, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opb520, DoEorB, DB, SdB, 2, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opb528, DoEorB, DB, SdB, 2, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opb530, DoEorB, DB, SdB, 2, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opb538, DoEorB, DB, SdB, 2, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opb540, DoEorW, DW, SdW, 2, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opb550, DoEorW, DW, SdW, 2, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opb558, DoEorW, DW, SdW, 2, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opb560, DoEorW, DW, SdW, 2, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opb568, DoEorW, DW, SdW, 2, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opb570, DoEorW, DW, SdW, 2, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opb578, DoEorW, DW, SdW, 2, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opb580, DoEorL, DL, SdL, 2, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opb590, DoEorL, DL, SdL, 2, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opb598, DoEorL, DL, SdL, 2, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opb5a0, DoEorL, DL, SdL, 2, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opb5a8, DoEorL, DL, SdL, 2, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opb5b0, DoEorL, DL, SdL, 2, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opb5b8, DoEorL, DL, SdL, 2, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opb700, DoEorB, DB, SdB, 3, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opb710, DoEorB, DB, SdB, 3, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opb718, DoEorB, DB, SdB, 3, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opb720, DoEorB, DB, SdB, 3, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opb728, DoEorB, DB, SdB, 3, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opb730, DoEorB, DB, SdB, 3, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opb738, DoEorB, DB, SdB, 3, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opb740, DoEorW, DW, SdW, 3, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opb750, DoEorW, DW, SdW, 3, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opb758, DoEorW, DW, SdW, 3, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opb760, DoEorW, DW, SdW, 3, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opb768, DoEorW, DW, SdW, 3, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opb770, DoEorW, DW, SdW, 3, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opb778, DoEorW, DW, SdW, 3, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opb780, DoEorL, DL, SdL, 3, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opb790, DoEorL, DL, SdL, 3, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opb798, DoEorL, DL, SdL, 3, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opb7a0, DoEorL, DL, SdL, 3, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opb7a8, DoEorL, DL, SdL, 3, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opb7b0, DoEorL, DL, SdL, 3, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opb7b8, DoEorL, DL, SdL, 3, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opb900, DoEorB, DB, SdB, 4, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opb910, DoEorB, DB, SdB, 4, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opb918, DoEorB, DB, SdB, 4, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opb920, DoEorB, DB, SdB, 4, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opb928, DoEorB, DB, SdB, 4, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opb930, DoEorB, DB, SdB, 4, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opb938, DoEorB, DB, SdB, 4, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opb940, DoEorW, DW, SdW, 4, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opb950, DoEorW, DW, SdW, 4, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opb958, DoEorW, DW, SdW, 4, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opb960, DoEorW, DW, SdW, 4, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opb968, DoEorW, DW, SdW, 4, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opb970, DoEorW, DW, SdW, 4, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opb978, DoEorW, DW, SdW, 4, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opb980, DoEorL, DL, SdL, 4, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opb990, DoEorL, DL, SdL, 4, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opb998, DoEorL, DL, SdL, 4, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opb9a0, DoEorL, DL, SdL, 4, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opb9a8, DoEorL, DL, SdL, 4, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opb9b0, DoEorL, DL, SdL, 4, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opb9b8, DoEorL, DL, SdL, 4, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opbb00, DoEorB, DB, SdB, 5, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opbb10, DoEorB, DB, SdB, 5, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opbb18, DoEorB, DB, SdB, 5, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opbb20, DoEorB, DB, SdB, 5, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opbb28, DoEorB, DB, SdB, 5, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opbb30, DoEorB, DB, SdB, 5, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opbb38, DoEorB, DB, SdB, 5, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opbb40, DoEorW, DW, SdW, 5, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opbb50, DoEorW, DW, SdW, 5, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opbb58, DoEorW, DW, SdW, 5, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opbb60, DoEorW, DW, SdW, 5, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opbb68, DoEorW, DW, SdW, 5, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opbb70, DoEorW, DW, SdW, 5, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opbb78, DoEorW, DW, SdW, 5, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opbb80, DoEorL, DL, SdL, 5, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opbb90, DoEorL, DL, SdL, 5, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opbb98, DoEorL, DL, SdL, 5, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opbba0, DoEorL, DL, SdL, 5, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opbba8, DoEorL, DL, SdL, 5, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opbbb0, DoEorL, DL, SdL, 5, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opbbb8, DoEorL, DL, SdL, 5, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opbd00, DoEorB, DB, SdB, 6, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opbd10, DoEorB, DB, SdB, 6, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opbd18, DoEorB, DB, SdB, 6, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opbd20, DoEorB, DB, SdB, 6, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opbd28, DoEorB, DB, SdB, 6, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opbd30, DoEorB, DB, SdB, 6, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opbd38, DoEorB, DB, SdB, 6, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opbd40, DoEorW, DW, SdW, 6, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opbd50, DoEorW, DW, SdW, 6, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opbd58, DoEorW, DW, SdW, 6, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opbd60, DoEorW, DW, SdW, 6, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opbd68, DoEorW, DW, SdW, 6, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opbd70, DoEorW, DW, SdW, 6, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opbd78, DoEorW, DW, SdW, 6, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opbd80, DoEorL, DL, SdL, 6, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opbd90, DoEorL, DL, SdL, 6, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opbd98, DoEorL, DL, SdL, 6, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opbda0, DoEorL, DL, SdL, 6, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opbda8, DoEorL, DL, SdL, 6, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opbdb0, DoEorL, DL, SdL, 6, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opbdb8, DoEorL, DL, SdL, 6, DL, DA, Ceaw, ins7, GML, SML, 26)

OperS(Opbf00, DoEorB, DB, SdB, 7, DB, DR, Cd, ins7, GRB, SRB, 4)
Oper (Opbf10, DoEorB, DB, SdB, 7, DB, DA, Cain, ins7, GMB, SMB, 12)
Oper (Opbf18, DoEorB, DB, SdB, 7, DB, DA, CaipB, ins7, GMB, SMB, 12)
Oper (Opbf20, DoEorB, DB, SdB, 7, DB, DA, CmaiB, ins7, GMB, SMB, 16)
Oper (Opbf28, DoEorB, DB, SdB, 7, DB, DA, Cdai, ins7, GMB, SMB, 16)
Oper (Opbf30, DoEorB, DB, SdB, 7, DB, DA, Caix, ins7, GMB, SMB, 20)
Oper (Opbf38, DoEorB, DB, SdB, 7, DB, DA, Ceaw, ins7, GMB, SMB, 18)
OperS(Opbf40, DoEorW, DW, SdW, 7, DW, DR, Cd, ins7, GRW, SRW, 4)
Oper (Opbf50, DoEorW, DW, SdW, 7, DW, DA, Cain, ins7, GMW, SMW, 12)
Oper (Opbf58, DoEorW, DW, SdW, 7, DW, DA, CaipW, ins7, GMW, SMW, 12)
Oper (Opbf60, DoEorW, DW, SdW, 7, DW, DA, CmaiW, ins7, GMW, SMW, 16)
Oper (Opbf68, DoEorW, DW, SdW, 7, DW, DA, Cdai, ins7, GMW, SMW, 16)
Oper (Opbf70, DoEorW, DW, SdW, 7, DW, DA, Caix, ins7, GMW, SMW, 20)
Oper (Opbf78, DoEorW, DW, SdW, 7, DW, DA, Ceaw, ins7, GMW, SMW, 18)
OperS(Opbf80, DoEorL, DL, SdL, 7, DL, DR, Cd, ins7, GRL, SRL, 8)
Oper (Opbf90, DoEorL, DL, SdL, 7, DL, DA, Cain, ins7, GML, SML, 20)
Oper (Opbf98, DoEorL, DL, SdL, 7, DL, DA, CaipL, ins7, GML, SML, 20)
Oper (Opbfa0, DoEorL, DL, SdL, 7, DL, DA, CmaiL, ins7, GML, SML, 24)
Oper (Opbfa8, DoEorL, DL, SdL, 7, DL, DA, Cdai, ins7, GML, SML, 24)
Oper (Opbfb0, DoEorL, DL, SdL, 7, DL, DA, Caix, ins7, GML, SML, 28)
Oper (Opbfb8, DoEorL, DL, SdL, 7, DL, DA, Ceaw, ins7, GML, SML, 26)

Oper (Op0000, DoOrB, DB, SimmB, 0, DB, DR, Cd, ins7, GRB, SRB, 8)
Oper (Op0010, DoOrB, DB, SimmB, 0, DB, DA, Cain, ins7, GMB, SMB, 16)
Oper (Op0018, DoOrB, DB, SimmB, 0, DB, DA, CaipB, ins7, GMB, SMB, 16)
Oper (Op0020, DoOrB, DB, SimmB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 20)
Oper (Op0028, DoOrB, DB, SimmB, 0, DB, DA, Cdai, ins7, GMB, SMB, 20)
Oper (Op0030, DoOrB, DB, SimmB, 0, DB, DA, Caix, ins7, GMB, SMB, 24)
OlogSR (Op0038, DoOrB, DoOrSR, 0, DB, SimmB, DB, GMB, SMB, GCB, SCB, 20)
Oper (Op0040, DoOrW, DW, SimmW, 0, DW, DR, Cd, ins7, GRW, SRW, 8)
Oper (Op0050, DoOrW, DW, SimmW, 0, DW, DA, Cain, ins7, GMW, SMW, 16)
Oper (Op0058, DoOrW, DW, SimmW, 0, DW, DA, CaipW, ins7, GMW, SMW, 16)
Oper (Op0060, DoOrW, DW, SimmW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 20)
Oper (Op0068, DoOrW, DW, SimmW, 0, DW, DA, Cdai, ins7, GMW, SMW, 20)
Oper (Op0070, DoOrW, DW, SimmW, 0, DW, DA, Caix, ins7, GMW, SMW, 24)
OlogSR (Op0078, DoOrW, DoOrSR, 1, DW, SimmW, DW, GMW, SMW, GCW, SCW, 20)
Oper (Op0080, DoOrL, DL, SimmL, 0, DL, DR, Cd, ins7, GRL, SRL, 16)
Oper (Op0090, DoOrL, DL, SimmL, 0, DL, DA, Cain, ins7, GML, SML, 28)
Oper (Op0098, DoOrL, DL, SimmL, 0, DL, DA, CaipL, ins7, GML, SML, 28)
Oper (Op00a0, DoOrL, DL, SimmL, 0, DL, DA, CmaiL, ins7, GML, SML, 32)
Oper (Op00a8, DoOrL, DL, SimmL, 0, DL, DA, Cdai, ins7, GML, SML, 32)
Oper (Op00b0, DoOrL, DL, SimmL, 0, DL, DA, Caix, ins7, GML, SML, 36)
Oper (Op00b8, DoOrL, DL, SimmL, 0, DL, DA, Ceaw, ins7, GML, SML, 34)

Oper (Op0200, DoAndB, DB, SimmB, 0, DB, DR, Cd, ins7, GRB, SRB, 8)
Oper (Op0210, DoAndB, DB, SimmB, 0, DB, DA, Cain, ins7, GMB, SMB, 16)
Oper (Op0218, DoAndB, DB, SimmB, 0, DB, DA, CaipB, ins7, GMB, SMB, 16)
Oper (Op0220, DoAndB, DB, SimmB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 20)
Oper (Op0228, DoAndB, DB, SimmB, 0, DB, DA, Cdai, ins7, GMB, SMB, 20)
Oper (Op0230, DoAndB, DB, SimmB, 0, DB, DA, Caix, ins7, GMB, SMB, 24)
OlogSR (Op0238, DoAndB, DoAndSR, 0, DB, SimmB, DB, GMB, SMB, GCB, SCB, 20)
Oper (Op0240, DoAndW, DW, SimmW, 0, DW, DR, Cd, ins7, GRW, SRW, 8)
Oper (Op0250, DoAndW, DW, SimmW, 0, DW, DA, Cain, ins7, GMW, SMW, 16)
Oper (Op0258, DoAndW, DW, SimmW, 0, DW, DA, CaipW, ins7, GMW, SMW, 16)
Oper (Op0260, DoAndW, DW, SimmW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 20)
Oper (Op0268, DoAndW, DW, SimmW, 0, DW, DA, Cdai, ins7, GMW, SMW, 20)
Oper (Op0270, DoAndW, DW, SimmW, 0, DW, DA, Caix, ins7, GMW, SMW, 24)
OlogSR (Op0278, DoAndW, DoAndSR, 1, DW, SimmW, DW, GMW, SMW, GCW, SCW, 20)
Oper (Op0280, DoAndL, DL, SimmL, 0, DL, DR, Cd, ins7, GRL, SRL, 16)
Oper (Op0290, DoAndL, DL, SimmL, 0, DL, DA, Cain, ins7, GML, SML, 28)
Oper (Op0298, DoAndL, DL, SimmL, 0, DL, DA, CaipL, ins7, GML, SML, 28)
Oper (Op02a0, DoAndL, DL, SimmL, 0, DL, DA, CmaiL, ins7, GML, SML, 32)
Oper (Op02a8, DoAndL, DL, SimmL, 0, DL, DA, Cdai, ins7, GML, SML, 32)
Oper (Op02b0, DoAndL, DL, SimmL, 0, DL, DA, Caix, ins7, GML, SML, 36)
Oper (Op02b8, DoAndL, DL, SimmL, 0, DL, DA, Ceaw, ins7, GML, SML, 34)

Oper (Op0a00, DoEorB, DB, SimmB, 0, DB, DR, Cd, ins7, GRB, SRB, 8)
Oper (Op0a10, DoEorB, DB, SimmB, 0, DB, DA, Cain, ins7, GMB, SMB, 16)
Oper (Op0a18, DoEorB, DB, SimmB, 0, DB, DA, CaipB, ins7, GMB, SMB, 16)
Oper (Op0a20, DoEorB, DB, SimmB, 0, DB, DA, CmaiB, ins7, GMB, SMB, 20)
Oper (Op0a28, DoEorB, DB, SimmB, 0, DB, DA, Cdai, ins7, GMB, SMB, 20)
Oper (Op0a30, DoEorB, DB, SimmB, 0, DB, DA, Caix, ins7, GMB, SMB, 24)
OlogSR (Op0a38, DoEorB, DoEorSR, 0, DB, SimmB, DB, GMB, SMB, GCB, SCB, 20)
Oper (Op0a40, DoEorW, DW, SimmW, 0, DW, DR, Cd, ins7, GRW, SRW, 8)
Oper (Op0a50, DoEorW, DW, SimmW, 0, DW, DA, Cain, ins7, GMW, SMW, 16)
Oper (Op0a58, DoEorW, DW, SimmW, 0, DW, DA, CaipW, ins7, GMW, SMW, 16)
Oper (Op0a60, DoEorW, DW, SimmW, 0, DW, DA, CmaiW, ins7, GMW, SMW, 20)
Oper (Op0a68, DoEorW, DW, SimmW, 0, DW, DA, Cdai, ins7, GMW, SMW, 20)
Oper (Op0a70, DoEorW, DW, SimmW, 0, DW, DA, Caix, ins7, GMW, SMW, 24)
OlogSR (Op0a78, DoEorW, DoEorSR, 1, DW, SimmW, DW, GMW, SMW, GCW, SCW, 20)
Oper (Op0a80, DoEorL, DL, SimmL, 0, DL, DR, Cd, ins7, GRL, SRL, 16)
Oper (Op0a90, DoEorL, DL, SimmL, 0, DL, DA, Cain, ins7, GML, SML, 28)
Oper (Op0a98, DoEorL, DL, SimmL, 0, DL, DA, CaipL, ins7, GML, SML, 28)
Oper (Op0aa0, DoEorL, DL, SimmL, 0, DL, DA, CmaiL, ins7, GML, SML, 32)
Oper (Op0aa8, DoEorL, DL, SimmL, 0, DL, DA, Cdai, ins7, GML, SML, 32)
Oper (Op0ab0, DoEorL, DL, SimmL, 0, DL, DA, Caix, ins7, GML, SML, 36)
Oper (Op0ab8, DoEorL, DL, SimmL, 0, DL, DA, Ceaw, ins7, GML, SML, 34)
